/**
 * Prisma configuration.
 *
 * Defines the file paths for the database schema, migrations, and seed scripts.
 * Also binds the datasource URL to the environment variable.
 */

// * This file was generated by Prisma and requires `prisma` and `dotenv`
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts"
  },
  datasource: {
    url: env("DATABASE_URL")
  }
});
