import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

import { isValidLocale } from "@/types/config";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const RootLayout = async (props: Props) => {
  const { locale } = await props.params;
  if (!isValidLocale(locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>{props.children}</NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
